### ISSUE TITLE
Add support for tracing to the example walkthrough

### ISSUE THREAD

**Issue by shukitchan** [apache/trafficserver-ingress-controller#20]
Let's use Jaegar to illustrate the support

**Comment by rishabhc** [comment]
PR #43 has been opened to add instructions to install Jaeger but not closing this issue since it needs more discussion on opentracing support

**Comment by shukitchan** [comment]
We will consider using the opentelemtry plugin for ATS - https://github.com/apache/trafficserver/tree/master/plugins/experimental/otel_tracer once it is released.

**Comment by shukitchan** [comment]
I have decided not to work on this feature in this project
